openapi: "3.1.0"
info:
  title: "Cardster API"
  description: "API for purchasing NFTs using Stripe, bypassing cryptocurrency transactions."
  license:
    name: "MIT"
  version: "1.0.0"
servers:
  - url: "https://cardster/api"
security:
  - bearerAuth: []
paths:
  /1/buy/stripe:
    post:
      description: "Allows users to buy NFTs using Stripe for credit card payments."
      parameters:
        - name: "nft_contract"
          in: "query"
          description: "Contract address and ID of the NFT in format 'address:id'."
          required: true
          schema:
            type: "string"
        - name: "owner_address"
          in: "query"
          description: "Ethereum address of the current NFT owner."
          required: true
          schema:
            type: "string"
        - name: "price"
          in: "query"
          description: "Price of the NFT."
          required: true
          schema:
            type: "number"
            format: "float"
        - name: "currency"
          in: "query"
          description: "Currency for the transaction (USD, EUR, etc.)."
          required: false
          schema:
            type: "string"
        - name: "recipient_address"
          in: "query"
          description: "Ethereum address where the NFT will be sent post-purchase."
          required: true
          schema:
            type: "string"
        - name: "blockchain"
          in: "query"
          description: "Blockchain on which the NFT is hosted."
          required: true
          schema:
            type: "string"
        - name: "nft_name"
          in: "query"
          description: "Name of the NFT that will be purchase"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "Successful transaction and NFT transfer."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  transaction_id:
                    type: "string"
                    description: "Transaction ID for the purchase."
                  nft_transfer_confirmation:
                    type: "string"
                    description: "Confirmation of the NFT transfer."
        "400":
          description: "Error or invalid request."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      required: ["error", "message"]
      type: "object"
      properties:
        error:
          type: "integer"
          format: "int32"
        message:
          type: "string"
  securitySchemes:
    bearerAuth:
      type: "http"
      scheme: "bearer"
